// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzxvrDUjy4Tsw7WRQxzTLAjj4EF4aSTGM',
    appId: '1:716443188058:web:cc28da6543ab1d0dad1163',
    messagingSenderId: '716443188058',
    projectId: 'bucketlistwithfirebase-eddef',
    authDomain: 'bucketlistwithfirebase-eddef.firebaseapp.com',
    storageBucket: 'bucketlistwithfirebase-eddef.appspot.com',
    measurementId: 'G-FPBNPCKYBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_X6_bROFRKtzjKsZThDQSv9Ojr0Qio18',
    appId: '1:716443188058:android:a8ed349d63a927bdad1163',
    messagingSenderId: '716443188058',
    projectId: 'bucketlistwithfirebase-eddef',
    storageBucket: 'bucketlistwithfirebase-eddef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8TFBmGwjQCLmw8M9CB9I9liK4tHfL05c',
    appId: '1:716443188058:ios:c87faf933c997568ad1163',
    messagingSenderId: '716443188058',
    projectId: 'bucketlistwithfirebase-eddef',
    storageBucket: 'bucketlistwithfirebase-eddef.appspot.com',
    iosClientId: '716443188058-8glnpo186ulbm00ee5kl11v34g1if930.apps.googleusercontent.com',
    iosBundleId: 'com.example.bucketListFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8TFBmGwjQCLmw8M9CB9I9liK4tHfL05c',
    appId: '1:716443188058:ios:c87faf933c997568ad1163',
    messagingSenderId: '716443188058',
    projectId: 'bucketlistwithfirebase-eddef',
    storageBucket: 'bucketlistwithfirebase-eddef.appspot.com',
    iosClientId: '716443188058-8glnpo186ulbm00ee5kl11v34g1if930.apps.googleusercontent.com',
    iosBundleId: 'com.example.bucketListFirebase',
  );
}
